### ISSUE TITLE
Thread-safe table, more powerful than guava's table

### ISSUE THREAD

**Issue by zjulzq** [wapatesh/fig#17]
Guava's table is useful, but it is not thread-safe.

**Comment by LeonLiuY** [comment]
Do you ask us to implement a `table`?

Maybe it is a good idea, but a little far from this project's purpose.

Fig's purpose is to make **basic** library.

In the future if we have enough resource, we may consider `table`.

**Comment by zjulzq** [comment]
Here `basic` means basic algorithm or common scenarios?

**Comment by LeonLiuY** [comment]
Basic means basic data types & structures.

Currently String, Array, Map are created. Because the use frequency is quite large.

I think table is far fewer used than those 3 types
