### ISSUE TITLE
Hash method list

### ISSUE THREAD

**Issue by RonaldoLee** [wapatesh/fig#2]
- [x] clear
- [x] containsKey
- [x] containsValue
- [x] entrySet
- [x] filter
- [x] get
- [x] isEmpty
- [x] invert
- [x] keySet
- [x] merge
- [x] put
- [x] putIfAbsent
- [x] reject
- [x] remove
- [x] replace
- [x] replaceAll
- [x] size
- [x] values
- [x] getKey  http://ruby-doc.org/core-2.2.0/Hash.html#method-i-key
- [x] merge (with another hash) http://ruby-doc.org/core-2.2.0/Hash.html#method-i-merge

**Comment by WangBoxue** [comment]
@liuyang1204 What's the difference between `filter` and `keepIf`?

**Comment by WangBoxue** [comment]
What's the difference between `reject` and `removeIf`, `filter` and `select`?

**Comment by LeonLiuY** [comment]
@WangBoxue I think basically they have no difference.

We need only implement 1 method.

@RonaldoLee You can remove `removeIf`, `select`, `keepIf`

**Comment by LeonLiuY** [comment]
All complete. Once we find new methods to fill, we make other issues.
