### ISSUE TITLE
Seq method list

### ISSUE THREAD

**Issue by WangBoxue** [wapatesh/fig#3]
- [x] map
- [x] mapWithIndex
- [x] first
- [x] last
- [x] join
- [x] sample
- [x] shuffle
- [x] forEachWithIndex
- [x] eachCons
- [x] forEachCons
- [x] order
- [x] distinct
- [x] findFirst
- [x] findLast
- [x] findFirstIndex
- [x] findLastIndex
- [x] push
- [x] prepend
- [x] concat
- [x] preConcat
- [x] of
- [x] newSeq
- [x] subSeq
- [x] reject
- [x] rejectWithIndex
- [x] filter
- [x] filterWithIndex
- [x] get
- [x] repeat
- [x] compact
- [x] count
- [x] countCondition
- [x] countConditionWithIndex
- [x] eachSlice http://ruby-doc.org/core-2.2.2/Enumerable.html#method-i-each_slice
- [x] forEachSlice
- [x] reduce http://ruby-doc.org/core-2.2.2/Enumerable.html#method-i-reduce
- [x] reverse
- [x] flatMap
- [x] eachCombination

**Comment by LeonLiuY** [comment]
You should check each item on, after the source code is merged. Otherwise this check list lost the meaning to ensure our progress.

**Comment by WangBoxue** [comment]
@liuyang1204 I'm writing code while adding methods to this list. All checked methods are already implemented in my local version.

**Comment by LeonLiuY** [comment]
I understand. Please take `merge into master` a serious step. Only if we merge your code into master, we can say it is implemented.

If something happened (Your code is not able to merge, or you take long vacation), this check list becomes useless.

And it is enough to send PR, after your finish 2 ~ 3 methods.

PR is preferred to be small.

**Comment by WangBoxue** [comment]
@liuyang1204 OK, I got it.

**Comment by LeonLiuY** [comment]
I added  some methods from `eachSlice` to `reverse`

**Comment by LeonLiuY** [comment]
All complete. Once we find new methods to fill, we make other issues.
